In [3]:
import pandas as pd 
import numpy as np 

df = pd.read_csv("N:\Download\student\student\student-mat.csv", sep=";")
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [4]:
df["Performance"] = np.where(df["G3"] >= 10, "Pass" , "Fail")

df[["G3", "Performance"]].head(10)

   G3 Performance
0   6        Fail
1   6        Fail
2  10        Pass
3  15        Pass
4  10        Pass
5  15        Pass
6  11        Pass
7   6        Fail
8  19        Pass
9  15        Pass

In [5]:
df["Performance"].value_counts()

Performance
Pass    265
Fail    130
Name: count, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

y = df["Performance"]
X = df.drop(columns=["G3", "Performance"])
X = pd.get_dummies(X, drop_first=True)

print("Features:", X.shape)
print("Target:", y.shape)

Features: (395, 41)
Target: (395,)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.30,
    random_state=123457,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 276
Testing samples: 119

In [8]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(random_state=123457)

model.fit(X_train, y_train)

print("Model training completed successfully.")

Model training completed successfully.

In [9]:
y_pred = model.predict(X_test)

print(y_pred[:20])

['Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Fail'
 'Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass']

In [10]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.8319327731092437

Confusion Matrix:
[[29 10]
 [10 70]]

Classification Report:
              precision    recall  f1-score   support

        Fail       0.74      0.74      0.74        39
        Pass       0.88      0.88      0.88        80

    accuracy                           0.83       119
   macro avg       0.81      0.81      0.81       119
weighted avg       0.83      0.83      0.83       119